### ISSUE TITLE
does this codebase support some recent causal discovery methods like, notears, dag-gnn,and so on

### ISSUE THREAD

**Issue by onlyonewater** [py-why/causal-learn#163]
hi, I am new in the causal discovery field, and I read some recent papers in this field, like notears [1], dag-gnn [2], and I find that this code base does not support these methods, so are there any plans to implement these algorithms in the future?

[1], DAGs with NO TEARS: Continuous optimization for structure learning](https://arxiv.org/abs/1803.01422)

[2],DAG-GNN: DAG Structure Learning with Graph Neural Networks

**Comment by kunwuz** [comment]
Thanks for your interest in causal discovery. Since we mainly focus on causal discovery algorithms with identifiability guarantees, there is no current plan to include the DAG structure learning algorithms you mentioned. However, I believe the Python implementations of these algorithms are available online if you would like to use them.

**Comment by onlyonewater** [comment]
ok, I got it, thanks!!
